#theme = "blowfish"
baseURL = "https://blog.alexotara.com"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 20
summaryLength = 30

enableGitInfo = true

buildDrafts = false
buildFuture = false

# googleAnalytics = "G-R5NDGF0KV2"

[permalinks]
  posts = '/:slug/' # for cleaner links

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]